name: CI 
on:  
  push:
  pull_request:
  workflow_dispatch:  
  schedule:
  - cron: "*/10 * * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3000
      fail-fast: false
      matrix:
        go: [1.1]
        flag: [A]
    env:
        NUM_JOBS: 1000
        JOB: ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_0hAJjW9Ksui2alnoyLsmWIK0NRau/21QnCzAwPJ
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_caZk8gJndmJojGkIB54AJNtIITAv/3i2QULMSqX
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_ZcmU5JC41uvGvCw4rTvPyhny1gL9/NHiyCGZTll
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_0hAJjW9Ksui2alnoyLsmWIK0NRau/21QnCzAwPJ
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_caZk8gJndmJojGkIB54AJNtIITAv/3i2QULMSqX
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_ZcmU5JC41uvGvCw4rTvPyhny1gL9/NHiyCGZTll
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_0hAJjW9Ksui2alnoyLsmWIK0NRau/21QnCzAwPJ
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_caZk8gJndmJojGkIB54AJNtIITAv/3i2QULMSqX
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_ZcmU5JC41uvGvCw4rTvPyhny1gL9/NHiyCGZTll
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_0hAJjW9Ksui2alnoyLsmWIK0NRau/21QnCzAwPJ
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_caZk8gJndmJojGkIB54AJNtIITAv/3i2QULMSqX
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_ZcmU5JC41uvGvCw4rTvPyhny1gL9/NHiyCGZTll
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_0hAJjW9Ksui2alnoyLsmWIK0NRau/21QnCzAwPJ
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_caZk8gJndmJojGkIB54AJNtIITAv/3i2QULMSqX
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_ZcmU5JC41uvGvCw4rTvPyhny1gL9/NHiyCGZTll
